name: Build firmware (PR)

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build (HackRF)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Git Submodule Update
        run: git submodule update --init --recursive

      - name: Build the Docker image
        run: docker build -t portapack-dev -f dockerfile-nogit .

      - name: Make build folder
        run: mkdir ${{ github.workspace }}/build

      - name: Run the Docker image
        run: docker run -e VERSION_STRING=pr_${{ github.event.pull_request.number || github.run_number }} -i -v ${{ github.workspace }}:/havoc portapack-dev

      - name: Upload DFU firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: portapack-mayhem-firmware-dfu
          path: build/firmware/portapack-mayhem-firmware.bin

      - name: Upload on-device Flash Utility artifact
        uses: actions/upload-artifact@v4
        with:
          name: portapack-mayhem-firmware-sdcard
          path: build/firmware/portapack-mayhem_OCI.ppfw.tar
